# Data Types 
1. Numeric Types: int,float
2. Boolean Type: bool
3. Sequence Types: list,tuple 

In [1]:
list_sample = [1,2,3,'a',3.3,True,'3']
print(list_sample)

[1, 2, 3, 'a', 3.3, True, '3']


In [2]:
print(type(list_sample)) # type(variable_name) is used to find the datatype of the variable

<class 'list'>


In [3]:
print(len(list_sample))

7


In [4]:
print(list_sample[4])# prints the 4th element present in the list

3.3


In [5]:
print(list_sample[0:3])# Slicing

[1, 2, 3]


In [6]:
list_sample.append(5)# adding item to list
print(list_sample)

[1, 2, 3, 'a', 3.3, True, '3', 5]


In [7]:
list_sample[5]="Hi"
print(list_sample)

[1, 2, 3, 'a', 3.3, 'Hi', '3', 5]


In [8]:
tuple_sample = (1,2,3,"hello",False,4.5,3)
print(tuple_sample)

(1, 2, 3, 'hello', False, 4.5, 3)


In [9]:
print(type(tuple_sample))

<class 'tuple'>


In [10]:
print(tuple_sample[2])

3


In [11]:
tuple_sample[2]=5

TypeError: 'tuple' object does not support item assignment

# Function In Python

In [12]:
def add(m,n):
    return m+n
result = add(4,5)
print(result)

9


# Condition Statement


a=5
if a>6:
    print(f"{a} is greater than 6")
else:
    print(f"{a} is less than 6")

In [13]:
a=input()
b=input()
if a>b:
    print(f"{a} is greater than {b}")
elif b>a:
    print(f"{a} is less than {b}")
else:
    print(f"{a} is equal to {b}")

5
6
5 is less than 6


# Loops


In [14]:
for i in range(5):
    print(i)
#     print(i,end=" ")

0
1
2
3
4


In [15]:
i=1
while i<5:
    print(i,end=" ")
    i+=1 # python does not support increment or decrement operator
    

1 2 3 4 

# Numpy

In [16]:
import numpy as np

In [17]:
arr_sample = np.array([1,2,3])
print(arr_sample)


[1 2 3]


In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# arr1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
# arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=float)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(arr.ndim)
# print(arr_sample.ndim)

2


In [20]:
print(arr.shape)# return number of (rows,columns)
print(arr.size)# returns number of elements in the array
print(arr.dtype)# to find the datatype of the element in the array

(3, 3)
9
int32


In [21]:
print(arr[1])
print(arr[1][2])

[4 5 6]
6


Initialisation:
1. empty()- returns an empty array with given size of random elements
2. eye()- returns array with diagonal elements as 1 while other as zeroes
3. identity()- returns identity matrix
4. ones()- returns array with all element as 1
5. zeroes()- returns array with all elements as 0

In [22]:
empty_arr = np.empty((2,3))
print(empty_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
eye_arr = np.eye(4,4,-1) 
eye_arr

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [24]:
identity_arr=np.identity(3)
identity_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
ones_arr = np.ones((3,4))
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Shape Manipulation :
1. ravel()-hepls us to return 1D array with all the input-array elements and with the same type as it
2. T-returns transpose of a matrix
3. reshape()- changes the shape of the array and needs to be stored in seperate variabe
4. resize()- changes shape of the array used

In [26]:
# print(arr)
print(arr.ravel())#

[1 2 3 4 5 6 7 8 9]


In [27]:
print(arr.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [28]:
print(arr.shape)
arr_reshape = arr.reshape((1,9))
arr

(3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.resize(9,1)

In [30]:
arr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [31]:
arr = np.array(range(0,40,2))
arr.resize((4,5))
arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

Important functions:
1. Slicing
2. sum()
3. max(),min() - returns max/min value
4. argmin(),argmax() - returns index of max/min value
5. sort
6. nonzero()- returns a tuple containing index of elements with nonzero values

In [32]:
arr[0:2,:] # returns values of row no. 0 and 1 along with all columns

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [33]:
arr[:,0:3] # returns array with 1st 3 columns of all rows

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24],
       [30, 32, 34]])

In [34]:
arr[:,::2]# selects columns from start till end with gap of 2

array([[ 0,  4,  8],
       [10, 14, 18],
       [20, 24, 28],
       [30, 34, 38]])

In [35]:
arr[:2,2:3]

array([[ 4],
       [14]])

In [36]:
arr.sum() 

380

In [37]:
print(arr.max())
print(arr.min())

38
0


In [38]:
print(arr.argmax())
print(arr.argmin())

19
0


In [39]:
arr = np.array([1,6,3,5,8,3,5,89,5,7])

In [40]:
np.sort?

In [41]:
np.sort(arr)#for incrasing order

array([ 1,  3,  3,  5,  5,  5,  6,  7,  8, 89])

In [42]:
np.sort(arr)[::-1]#for decresing order

array([89,  8,  7,  6,  5,  5,  5,  3,  3,  1])

In [43]:
arr = np.array([1,0,9,8,0,7,0])
# arr = np.array([[1,3,0,3,4,0],[0,3,0,5,6,7]])
arr

array([1, 0, 9, 8, 0, 7, 0])

In [44]:
print(arr.nonzero())

(array([0, 2, 3, 5], dtype=int64),)
